
pipeline {
    agent none
    stages {
      stage('Build'){
        agent {
          docker {
            image 'python:3.9.9-alpine'
          }
        }
        steps {
          sh 'python -m py_compile sources/add2vals.py sources/calc.py'  
        }
      }
    }
  }
